name: nectar_mac
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
    sdk: '>=2.19.0-444.2.beta <3.0.0'
dependencies:
    flutter:
        sdk: flutter
    flutter_localizations: # Add this line
        sdk: flutter         # Add this line
    intl: ^0.18.0 # Add this line
    cupertino_icons: ^1.0.2
    firebase_core:
    firebase_auth:
    intl_phone_field:
    # banner_carousel: ^1.2.1
    http:
    sliding_up_panel2:
    equatable:
    dartz:
    flutter_bloc:
    cached_network_image:
    get_it:
    shared_preferences:
    internet_connection_checker:
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
flutter:
    uses-material-design: true
    assets:
        - assets/images/intro/
        - assets/images/home/
        - assets/images/auth/
        - assets/images/products/
        - assets/images/categories/
        - assets/images/resturant/
        - assets/images/
        - assets/icons/
        - assets/json/
        - assets/locales/
        - assets/sounds/
        - assets/videos/
        - assets/svg/
        - assets/languages/
    fonts:
        -
            family: Gilroy
            fonts:
                -
                    asset: assets/fonts/gilroy/Gilroy-Regular.ttf
                -
                    asset: assets/fonts/gilroy/Gilroy-RegularItalic.ttf
                    style: italic
                -
                    asset: assets/fonts/gilroy/Gilroy-Medium.ttf
                    weight: 400
                -
                    asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
                    weight: 500 
                -
                    asset: assets/fonts/gilroy/Gilroy-Bold.ttf
                    weight: 600
                -
                    asset: assets/fonts/gilroy/Gilroy-ExtraBold.ttf
                    weight: 700
                -
                    asset: assets/fonts/gilroy/Gilroy-Black.ttf
                    weight: 900 