name: nectar_mac
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
    sdk: '>=2.19.0-444.2.beta <3.0.0'
dependencies:
    flutter:
        sdk: flutter
    flutter_localizations: # Add this line
        sdk: flutter         # Add this line
    intl: ^0.17.0 # Add this line
    cupertino_icons: ^1.0.2
    firebase_core: ^2.4.1
    firebase_auth: ^4.2.4
    intl_phone_field: ^3.1.0
    # banner_carousel: ^1.2.1
    http: ^0.13.5
    sliding_up_panel2: ^3.2.2
    equatable: ^2.0.5
    dartz: ^0.10.1
    flutter_bloc: ^8.1.1
    cached_network_image: ^3.2.3
    get_it: ^7.2.0
    shared_preferences: ^2.0.17
    internet_connection_checker: ^1.0.0+1
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
flutter:
    uses-material-design: true
    assets:
        - assets/images/intro/
        - assets/images/home/
        - assets/images/auth/
        - assets/images/products/
        - assets/images/categories/
        - assets/images/resturant/
        - assets/images/
        - assets/icons/
        - assets/json/
        - assets/locales/
        - assets/sounds/
        - assets/videos/
        - assets/svg/
        - assets/languages/
    fonts:
        -
            family: Gilroy
            fonts:
                -
                    asset: assets/fonts/gilroy/Gilroy-Regular.ttf
                -
                    asset: assets/fonts/gilroy/Gilroy-RegularItalic.ttf
                    style: italic
                -
                    asset: assets/fonts/gilroy/Gilroy-Medium.ttf
                    weight: 400
                -
                    asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
                    weight: 500 
                -
                    asset: assets/fonts/gilroy/Gilroy-Bold.ttf
                    weight: 600
                -
                    asset: assets/fonts/gilroy/Gilroy-ExtraBold.ttf
                    weight: 700
                -
                    asset: assets/fonts/gilroy/Gilroy-Black.ttf
                    weight: 900 