# Generated by Django 4.1.5 on 2023-01-07 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Language', '0001_initial'),
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='geo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Address', to='Location.geo', verbose_name='Location'),
        ),
        migrations.RemoveField(
            model_name='country',
            name='languages',
        ),
        migrations.AddField(
            model_name='country',
            name='languages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Countries', to='Language.language', verbose_name='languages'),
        ),
    ]
