# Generated by Django 4.1.5 on 2023-01-24 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='languages',
            new_name='language',
        ),
    ]
