# Generated by Django 4.1.5 on 2023-01-07 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
        ('Location', '0002_alter_address_geo_remove_country_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='geo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Address', to='Location.geo', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Address', to='Location.street', verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Capital To +', to='Location.city', verbose_name='Capital'),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Countries', to='Payment.currency', verbose_name='Currency'),
        ),
    ]
