# Generated by Django 4.1.5 on 2023-01-06 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Location', '0001_initial'),
        ('Card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('serial_no', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Serial Number')),
                ('received_date', models.DateTimeField(auto_now_add=True, verbose_name='Received Date')),
                ('is_received', models.BooleanField(default=False, verbose_name='is Received')),
                ('is_refund_requested', models.BooleanField(default=False, verbose_name='is Refund Requested')),
                ('is_refund_granted', models.BooleanField(default=False, verbose_name='is Refund Granted')),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='Location.address', verbose_name='Billing Address')),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Card.card', verbose_name='Customer')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='Location.address', verbose_name='Shipping Address')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='is Accepted')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Refunds', to='Invoice.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
            },
        ),
    ]
