# Generated by Django 4.1.5 on 2023-01-07 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'category_parent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sub_Categories+', to='Category.category', verbose_name='Category Parent'),
        ),
    ]
