# Generated by Django 4.1.5 on 2023-01-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_alter_category_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Sub_Categories',
            field=models.ManyToManyField(to='Category.category', verbose_name='Sub Categories'),
        ),
    ]
