# Generated by Django 4.1.5 on 2023-01-07 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0003_category_sub_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Sub_Categories',
            field=models.ManyToManyField(limit_choices_to={'category_parent__isnull': False}, to='Category.category', verbose_name='Sub Categories'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'category_parent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Category.category', verbose_name='Category Parent'),
        ),
    ]
