# Generated by Django 4.1.1 on 2022-09-20 19:25

import Lab.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Lab.models.upload_to, verbose_name='Image')),
                ('availability', models.CharField(max_length=30, null=True, verbose_name='Availability')),
                ('price', models.FloatField(verbose_name='Price')),
                ('describtion', models.TextField(max_length=1000, verbose_name='Describtion')),
                ('reviews', models.SmallIntegerField(null=True, verbose_name='Reviews')),
                ('star', models.SmallIntegerField(null=True, verbose_name='Star')),
            ],
            options={
                'verbose_name': 'Vegetable',
                'verbose_name_plural': 'Vegetables',
                'permissions': [('can_add_new_project', 'can add new project'), ('dg_view_project', 'OLP can view project')],
            },
        ),
        migrations.CreateModel(
            name='VegetableImage',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Lab.models.upload_to, verbose_name='Image')),
                ('vegetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vegetable.vegetable', verbose_name='Vegetable')),
            ],
            options={
                'verbose_name': 'Vegetable Image',
                'verbose_name_plural': 'Vegetable Images',
            },
        ),
    ]
