# Generated by Django 4.1.5 on 2023-01-10 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Ch', 'Check'), ('P', 'PayPal'), ('S', 'Stripe'), ('Ca', 'Cach')], max_length=2, verbose_name='Payment Method')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cearted At')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('promo_code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('discount', models.FloatField(verbose_name='Discount')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='LineInCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Card.card', verbose_name='Card')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='In_Cards', to='Product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Line In Card',
                'verbose_name_plural': 'Lines In Card',
            },
        ),
    ]
