# Generated by Django 4.1.5 on 2023-01-06 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Card', '0001_initial'),
        ('Product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='card',
            name='products',
            field=models.ManyToManyField(through='Card.LineInCard', to='Product.product', verbose_name='Products'),
        ),
        migrations.AddField(
            model_name='card',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Card.coupon', verbose_name='Promo Code'),
        ),
        migrations.AlterUniqueTogether(
            name='lineincard',
            unique_together={('card', 'product')},
        ),
    ]
