# Generated by Django 4.1.5 on 2023-01-10 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Card', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineincard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lines_In_Card', to='Card.card', verbose_name='Card'),
        ),
    ]
