# Generated by Django 4.1.5 on 2023-01-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card', '0003_alter_lineincard_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='is Finished'),
        ),
        migrations.AlterField(
            model_name='card',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Ch', 'Check'), ('P', 'PayPal'), ('S', 'Stripe'), ('Ca', 'Cach')], max_length=2, null=True, verbose_name='Payment Method'),
        ),
    ]
