# Generated by Django 4.1.5 on 2023-01-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card', '0004_card_is_finished_alter_card_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineincard',
            name='amount',
            field=models.SmallIntegerField(verbose_name='Amount'),
        ),
    ]
