# Generated by Django 4.1.5 on 2023-02-14 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Location', '0002_rename_languages_country_language'),
        ('MyCart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('serial_no', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Serial Number')),
                ('received_date', models.DateTimeField(auto_now_add=True, verbose_name='Received Date')),
                ('is_received', models.BooleanField(default=False, verbose_name='is Received')),
                ('is_refund_requested', models.BooleanField(default=False, verbose_name='is Refund Requested')),
                ('is_refund_granted', models.BooleanField(default=False, verbose_name='is Refund Granted')),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Billing_Orders', to='Location.address', verbose_name='Billing Address')),
                ('my_cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='MyCart.mycart', verbose_name='My Cart')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Shipping_Orders', to='Location.address', verbose_name='Shipping Address')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='is Accepted')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Refund', to='Order.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
            },
        ),
    ]
