# Generated by Django 4.1.5 on 2023-02-17 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyCart', '0002_initial'),
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='my_cart',
            field=models.OneToOneField(limit_choices_to={'is_finished': True}, on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='MyCart.mycart', verbose_name='My Cart'),
        ),
    ]
