# Generated by Django 4.1.5 on 2023-02-17 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_alter_order_my_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PromoCode',
            new_name='PromoCard',
        ),
        migrations.AlterModelOptions(
            name='promocard',
            options={'verbose_name': 'Promo Card', 'verbose_name_plural': 'Promo Cards'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='promo_code',
        ),
        migrations.AddField(
            model_name='order',
            name='promo_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order.promocard', verbose_name='Promo Card'),
        ),
    ]
