# Generated by Django 4.1.5 on 2023-02-04 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
        ('Location', '0002_rename_languages_country_language'),
        ('Order', '0002_remove_order_card_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Orders', to='Location.address', verbose_name='Billing Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='Cart.cart', verbose_name='Cart'),
        ),
    ]
