# Generated by Django 4.1.5 on 2023-02-04 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0002_rename_languages_country_language'),
        ('Order', '0003_alter_order_billing_address_alter_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Billing_Orders', to='Location.address', verbose_name='Billing Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Shipping_Orders', to='Location.address', verbose_name='Shipping Address'),
        ),
    ]
