# Generated by Django 4.1.5 on 2023-02-17 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_rename_promocode_promocard_alter_promocard_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='promo_card',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
    ]
