# Generated by Django 4.1.5 on 2023-01-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
        ('Language', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='applicatins_support',
            field=models.ManyToManyField(related_name='Language_Supported', to='Application.application', verbose_name='Applicatins Support'),
        ),
    ]
