# Generated by Django 4.1.5 on 2023-01-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Language', '0002_language_applicatins_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='emoji',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Emoji'),
        ),
    ]
