# Generated by Django 4.1.5 on 2023-01-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
        ('Language', '0003_language_emoji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='applicatins_support',
        ),
        migrations.AddField(
            model_name='language',
            name='applications_support',
            field=models.ManyToManyField(related_name='Language_Supported', to='Application.application', verbose_name='Applications Support'),
        ),
    ]
