# Generated by Django 4.1.5 on 2023-02-14 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0003_alter_productimage_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('promo_code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('discount', models.FloatField(verbose_name='Discount')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Last Update')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='MyCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('payment_method', models.CharField(blank=True, choices=[('Ch', 'Check'), ('P', 'PayPal'), ('S', 'Stripe'), ('Ca', 'Cach')], max_length=2, null=True, verbose_name='Payment Method')),
                ('is_finished', models.BooleanField(default=False, verbose_name='is Finished')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='My_Carts', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'My Cart',
                'verbose_name_plural': 'My Carts',
            },
        ),
        migrations.CreateModel(
            name='MyCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('amount', models.SmallIntegerField(verbose_name='Amount')),
                ('my_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='My_Cart_Items', to='MyCart.mycart', verbose_name='My Cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='My_Carts_Products', to='Product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'My Cart Item',
                'verbose_name_plural': 'My Cart Items',
                'unique_together': {('my_cart', 'product')},
            },
        ),
        migrations.AddField(
            model_name='mycart',
            name='my_cart_items',
            field=models.ManyToManyField(through='MyCart.MyCartItem', to='Product.product', verbose_name='My Cart Items'),
        ),
        migrations.AddField(
            model_name='mycart',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyCart.coupon', verbose_name='Promo Code'),
        ),
    ]
