# Generated by Django 4.1.5 on 2023-02-15 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('is_finished', models.BooleanField(default=False, verbose_name='is Finished')),
            ],
            options={
                'verbose_name': 'My Cart',
                'verbose_name_plural': 'My Carts',
            },
        ),
        migrations.CreateModel(
            name='MyCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('amount', models.FloatField(default=1, verbose_name='Amount')),
                ('my_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='My_Cart_Items', to='MyCart.mycart', verbose_name='My Cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_cart', to='Product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'My Cart Item',
                'verbose_name_plural': 'My Cart Items',
            },
        ),
    ]
