# Generated by Django 4.1.5 on 2023-02-15 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MyCart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='My_Carts', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Customer'),
        ),
        migrations.AlterUniqueTogether(
            name='mycartitem',
            unique_together={('my_cart', 'product')},
        ),
    ]
