# Generated by Django 4.1.5 on 2023-02-15 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
        ('MyCart', '0001_initial'),
        ('Order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='My_Carts', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='mycart',
            name='my_cart_items',
            field=models.ManyToManyField(through='MyCart.MyCartItem', to='Product.product', verbose_name='My Cart Items'),
        ),
        migrations.AddField(
            model_name='mycart',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.order', verbose_name='Order'),
        ),
        migrations.AlterUniqueTogether(
            name='mycartitem',
            unique_together={('my_cart', 'product')},
        ),
    ]
