# Generated by Django 4.1.5 on 2023-02-17 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorites_products',
        ),
    ]
