# Generated by Django 4.1.5 on 2023-02-17 12:47

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_alter_order_my_cart'),
        ('User', '0002_remove_profile_favorites_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='my_orders',
            field=models.ManyToManyField(limit_choices_to={'my_cart__customer': User.models.User}, to='Order.order', verbose_name='My Orders'),
        ),
    ]
