# Generated by Django 4.1.5 on 2023-02-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_profile_my_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='my_orders',
        ),
    ]
