# Generated by Django 4.1.5 on 2023-01-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_is_verfied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verfied',
            new_name='is_verified',
        ),
    ]
