# Generated by Django 4.1.5 on 2023-02-17 15:31

import Nectar.methods
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_remove_profile_my_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Nectar.methods.upload_to, verbose_name='Image'),
        ),
    ]
