# Generated by Django 4.1.5 on 2023-01-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_productimage_product'),
        ('User', '0004_rename_is_verfied_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites_products',
            field=models.ManyToManyField(to='Product.product', verbose_name='Favorite Products'),
        ),
    ]
