# Generated by Django 4.1.5 on 2023-02-17 18:54

import User.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_remove_order_billing_address_remove_order_promo_card_and_more'),
        ('Location', '0001_initial'),
        ('User', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='my_basket',
        ),
        migrations.AddField(
            model_name='profile',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Location.address', verbose_name='Billing Address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Location.address', verbose_name='Delivery Address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='promo_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order.promocard', verbose_name='Promo Card'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=User.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='User'),
        ),
    ]
