# Generated by Django 4.1.5 on 2023-02-17 18:54

import User.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifecation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=300, verbose_name='ISO_639_1')),
                ('user', models.ForeignKey(default=User.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='Notifecations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notifecation',
                'verbose_name_plural': 'Notifecations',
            },
        ),
    ]
