# Generated by Django 4.1.5 on 2023-02-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifecation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifecation',
            name='message',
            field=models.TextField(max_length=300, verbose_name='Message'),
        ),
    ]
