# Generated by Django 4.1.5 on 2023-01-10 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
                ('native', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Native')),
                ('symbol', models.CharField(max_length=2, unique=True, verbose_name='Symbol')),
                ('power', models.IntegerField(verbose_name='Power')),
            ],
            options={
                'verbose_name': 'Prefix',
                'verbose_name_plural': 'Prefixes',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
                ('native', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Native')),
                ('symbol', models.CharField(max_length=5, unique=True, verbose_name='Symbol')),
                ('measurement', models.CharField(blank=True, choices=[('P', 'Package'), ('V', 'Volume'), ('A', 'Area'), ('L', 'Length'), ('M', 'Mass'), ('C', 'Concentation'), ('S', 'Speed'), ('T', 'Time'), ('D', 'Direction'), ('Te', 'Temperature'), ('EC', 'Electric Current'), ('LI', 'Luminous Intensity')], max_length=2, null=True, verbose_name='Measurement')),
                ('base_unit', models.ForeignKey(blank=True, limit_choices_to={'prefix__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sub_Units', to='Unit.unit', verbose_name='Base Unit')),
                ('prefix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Units', to='Unit.prefix', verbose_name='Prefix')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
    ]
